### ISSUE TITLE
this has an R version here

### ISSUE THREAD

**Issue by pachadotdev** [cid-harvard/py-ecomplexity#11]
hi

glad to have discovered this!! I have done something very similar with extensions from recent articles here
https://github.com/pachamaltese/economiccomplexity

**Comment by shreyasgm** [comment]
Thank you very much for your contribution! I'm going to keep this issue open till I'm able to find some time to validate your package against ours.

**Comment by shreyasgm** [comment]
This R version uses Fitness as the default method to calculate economic complexity, which is not appropriate for our default use case.

**Comment by pachadotdev** [comment]
> This R version uses Fitness as the default method to calculate economic complexity, which is not appropriate for our default use case.

hi, you can switch to eigenvalues or reflections by changing the parameter ;)

**Comment by shreyasgm** [comment]
Of course, I was referring to the default value for the `method` argument in `complexity_measures`.
