### ISSUE TITLE
Explicitly specify "name" in MultiIndex.from_product

### ISSUE THREAD

**Issue by complexly** [cid-harvard/py-ecomplexity#12]
In line 69 of proximity.py, better to specify names explicitly
https://github.com/cid-harvard/py-ecomplexity/blob/05076fb21b4789c8468f3b21a9b95ffd192cd5c4/ecomplexity/proximity.py#L69

After upgrading to pandas 1.0+, pd.MultiIndex.from_product tries to infer names, which seems to cause error when running reset_index later.

**Comment by shreyasgm** [comment]
Thanks, Yang! Do you want to open a PR for this?
