### ISSUE TITLE
Help with the subnational data

### ISSUE THREAD

**Issue by kmaksatk** [cid-harvard/py-ecomplexity#16]
Good day, huge thanks for your work! We are a group of data scientists trying to calculate ECI, PCI and proximity between products for specific country, but we are getting weird results, especially for the proximity. Therefore, we have several questions:

Is there any tuning needed for calculation of the proximity at subnational level?
Could you share the data that you used for your analysis?
Could you elaborate more on the calculation of the subnational data?
Is there anyone with whom we can get in contact to have q&a session?

Thank you in advance, your help will be very much appreciated!

**Comment by shreyasgm** [comment]
Sorry for getting to this so late. Responding for others who may have arrived here:

If you have specific questions about the Dataverse data and the metrics available there, please reach out to the team that manages the [Atlas](https://atlas.cid.harvard.edu/)

Main point to note here is that the data provided through the Dataverse goes through a lot of pre-processing and cleaning before the corresponding economic complexity metrics are generated, and you should not expect to reproduce those metrics without those cleaning steps.

Sub-national complexity analysis is an ongoing research area and I do not have finished publications ready to share.
