### ISSUE TITLE
RCA calculation

### ISSUE THREAD

**Issue by manapshymyr** [cid-harvard/py-ecomplexity#18]
Hello. Thanks for your great job. 

I am confused when you are calculating the RCA.

                num = data_np / np.nansum(data_np, axis=1)[:, np.newaxis]
                
                loc_total = np.nansum(data_np, axis=0)[np.newaxis, :]
                world_total = np.nansum(loc_total, axis=1)[:, np.newaxis]
                den = loc_total / world_total
                self.rca_t = num / den

Should not it be something like "(product p  value/ local_total c)/(product p total/world total) No?

**Comment by shreyasgm** [comment]
Note that (x/a)/(b/y) = (x/b)/(a/y)

**Comment by matuteiglesias** [comment]
Also sometimes useful:  = x / (a b / y)
