### ISSUE TITLE
PCI calculation.

### ISSUE THREAD

**Issue by manapshymyr** [cid-harvard/py-ecomplexity#19]
Dear team,

I was wondering about the PCI calculation. You have a equation:
```
 cdata.pci_t = (cdata.pci_t - cdata.eci_t.mean()) / cdata.eci_t.std()

cdata.eci_t = (cdata.eci_t - cdata.eci_t.mean()) / cdata.eci_t.std()
```
Shouldn't it be  `cdata.pci_t = (cdata.pci_t - cdata.pci_t.mean()) / cdata.pci_t.std()` according to the https://growthlab.cid.harvard.edu/files/growthlab/files/atlas_2013_part1.pdf , page 24.?

**Comment by shreyasgm** [comment]
Refer https://github.com/cid-harvard/ecomplexity/issues/3

**Comment by manapshymyr** [comment]
> Refer [cid-harvard/ecomplexity#3](https://github.com/cid-harvard/ecomplexity/issues/3)

will this `cdata.pci_t = (cdata.pci_t - cdata.pci_t.mean()) / cdata.pci_t.std()`  be correct for PCI calculation?

**Comment by shreyasgm** [comment]
The "correct" values are the ones the package outputs (with the ECI mean / std used for normalization). You can also work with the unnormalized indices themselves - the normalization is just a statistical treatment on top that lets us get the nice property described in the books and the link I sent above.
