### ISSUE TITLE
Possible mistake in the code of ecomplexity.py

### ISSUE THREAD

**Issue by tomleung1996** [cid-harvard/py-ecomplexity#23]
Hi,

I found a possible mistake in line #209 of `ecomplexity.py`. According to the book _The atlas of economic complexity_, both `ECI` and `PCI` should be z-score normalized. While the code normalizes `ECI` correctly, resulting in mean=0 and std=1, the `PCI` does not.

In line #209, `PCI` is normalized using the mean and standard deviation of `ECI`. I thought it might be a mistake? Though it does not harm the rankings.

Thank you!

**Comment by tomleung1996** [comment]
Also, I am confused about line #90-93, which is suggested to "Adjust sign of ECI and PCI so it makes sense, as per book". I could not find this procedure in _The atlas of economic complexity_. 

Could you help me with that?

**Comment by shreyasgm** [comment]
Refer #19
