### ISSUE TITLE
PCI normalization using wrong mean and standard deviation. 

### ISSUE THREAD

**Issue by dauletgali** [cid-harvard/py-ecomplexity#25]
Good day, thank you a lot for this project

I came across with a problem that mean and std of the PCI is not 0 and 1. I have looked at the source code and realized that in the function ecomplexity (file ecomplexity.py) line 209,

```python 
# Normalize variables as per STATA package
cdata.pci_t = (cdata.pci_t - cdata.eci_t.mean()) / cdata.eci_t.std()
cdata.cog_t = cdata.cog_t / cdata.eci_t.std()
cdata.eci_t = (cdata.eci_t - cdata.eci_t.mean()) / cdata.eci_t.std()
```

PCI data normalized by the ECI mean and std. Is it mistake or it is done purposefully ? For now my pci ranges from [-10,6] which seems very unusual. Thanks !

**Comment by dauletgali** [comment]
I think it should be 
```python 
cdata.pci_t = (cdata.pci_t - cdata.pci_t.mean()) / cdata.pci_t.std()
```

**Comment by SultanOrazbayev** [comment]
See this issue in the stata version: https://github.com/cid-harvard/ecomplexity/issues/3 (related issue was closed earlier here https://github.com/cid-harvard/py-ecomplexity/issues/19).

**Comment by dauletgali** [comment]
@SultanOrazbayev 
Thank you for reply 
Рахмет!
