### ISSUE TITLE
Economic density over 1

### ISSUE THREAD

**Issue by hydrophis-spiralis** [cid-harvard/py-ecomplexity#6]
I managed to produce economic density values greater than 1.
How I managed to do it:
I'm currently in the process of making economic complexity analysis for one of regions of Russian Federation. 
* I managed to get export and import volumes for particular region.
* Substracted region export values from Russian exports and and region imports from Russian imports.
* Introduced region as separate country.
* Rest of the world was merged into "world" label

Run of `ecomplexity` produced values greater than 1 for some of goods(I use hs07 4-digits codes for that), which seams impossible - formula itself does not allow values greater than 1.

Data itself is here: https://www.dropbox.com/s/9h6kdny04w0kkt2/world_data_kgd.csv?dl=0

**Comment by shreyasgm** [comment]
Thank you for bringing this to our attention. Could you please provide a couple of specifics?

- Specify which formula you are referring to
- Provide code to reproduce the issue

**Comment by shreyasgm** [comment]
@hydrophis-spiralis do let us know the above details (especially the formula that you refer to).
