### ISSUE TITLE
name 'ecomplexity' is not defined

### ISSUE THREAD

**Issue by akozzy18** [cid-harvard/py-ecomplexity#9]
I am currently running the init_ file and I the error, "NameError: name 'ecomplexity' is not defined", how would I solve this?

**Comment by shreyasgm** [comment]
If you're just trying to use the package, all you need to do is do `pip install ecomplexity` in the terminal, and then `from ecomplexity import ecomplexity` in your script. Can you clarify what you're trying to do?

**Comment by shreyasgm** [comment]
Closing as not an issue. @akozzy18 let me know if you have any trouble using the package.
